#ifndef __CONFIG_H
#define __CONFIG_H
#define LK 1
#define MTK_GPT_SCHEME_SUPPORT
#define WITH_DEBUG_UART 1
#define MTK_NEW_COMBO_EMMC_SUPPORT
#define MTK_MT6370_PMU
#define MTK_MD1_SUPPORT 14
#define MTK_MD3_SUPPORT 0
#define MTK_C2K_LTE_MODE 0
#define RAT_CONFIG_LTE_SUPPORT
#define BUILD_LK
#define SKIP_MTK_PARTITION_HEADER_CHECK
#define MTK_GPT_SCHEME_SUPPORT
#define MEMBASE 0X56000000
#define SCRATCH_ADDR 0X56900000
#define SCRATCH_SIZE 0X08000000
#define MEMSIZE 0X00400000
#define MTK_LM_MODE
#define DEVICE_TREE_SUPPORT
#define MTK_FASTBOOT_SUPPORT
#define MTK_DLPT_SUPPORT
#define PLATFORM_SECURITY_VERSION 21
#define GPT_VER 4
#define KERNEL_DECOMPRESS_SIZE 0X0C800000
#define ENABLE_IO_THREAD
#define PLATFORM "MT6763"
#define SELINUX_STATUS 3
#define PERIPH_BLK_BLSP 1
#define WITH_CPU_EARLY_INIT 0
#define WITH_CPU_WARM_BOOT 0
#define MMC_SLOT 1
#define MTK_CAN_FROM_CLUSTER1 1
#define MTK_PMIC_FULL_RESET
#define CFG_DTB_EARLY_LOADER_SUPPORT 1
#define MTK_3LEVEL_PAGETABLE
#define MBLOCK_LIB_SUPPORT 2
#define PLAT_DBG_INFO_LIB_SUPPORT 1
#define MTK_SECURITY_SW_SUPPORT
#define MTK_POWER_ON_WRITE_PROTECT 1
#define MTK_SEC_FASTBOOT_UNLOCK_SUPPORT
#define MTK_OFF_MODE_CHARGE_SUPPORT
#define MTK_SMC_K32_SUPPORT
#define MTK_MRDUMP_SRAM_CB
#define MTK_MRDUMP_USB_DUMP
#define FHDPLUS2340
#define MTK_POWER_ON_WP
#define MTK_PARTITION_COMMON
#define MTK_SMI_SUPPORT
#define MTK_TINYSYS_SSPM_SUPPORT
#define SPM_FW_USE_PARTITION
#define MTK_USB2JTAG_SUPPORT
#define MTK_KERNEL_POWER_OFF_CHARGING
#define MTK_PUMP_EXPRESS_PLUS_SUPPORT
#define PRIZE_WIRELESS_RECEIVER_MAXIC_MT5715
#define MTK_MT6370_PMU_CHARGER_SUPPORT
#define SWCHR_POWER_PATH
#define MTK_MT6370_PMU_BLED_SUPPORT
#define MTK_CHARGER_INTERFACE
#define LK_OPT_TO_KERNEL_CCCI
#define LK_LD_MD_SUPPORT
#define ENABLE_PARSING_LK_ENV
#define MTK_PROTOCOL1_RAT_CONFIG "LF_W_G"
#define MTK_LK_REGISTER_WDT
#define MTK_AEE_PLATFORM_DEBUG_SUPPORT
#define PART_DEV_API_V2
#define ARM_CPU_CORTEX_A53 1
#define ARM_WITH_CP15 1
#define ARM_WITH_MMU 1
#define ARM_ISA_ARMV7 1
#define ARM_WITH_VFP 1
#define ARM_WITH_NEON 1
#define ARM_WITH_THUMB 1
#define ARM_WITH_THUMB2 1
#define ARM_WITH_CACHE 1
#define ARM_WITH_L2 1
#define USER_BUILD
#define MTK_RC_TO_VENDOR
#define MTK_ATM_SUPPORT
#define SYSTEM_AS_ROOT
#define LOG_STORE_SUPPORT
#define MTK_ULTRA_FLASH
#define MTK_MRDUMP_SUPPORT
#define HX83112_FHDP_DSI_VDO_AUO
#define MTK_LCM_PHYSICAL_ROTATION "0"
#define LCM_WIDTH ""
#define LCM_HEIGHT ""
#define LCM_SET_DISPLAY_ON_DELAY Y
#define MACH_TYPE 6763
#define BOARD K63V2_64_BSP
#define PROJECT_K63V2_64_BSP 1
#define TARGET_K63V2_64_BSP 1
#define PLATFORM_MT6763 1
#define ARCH_ARM 1
#define MACH_TYPE_MT6763 1
#define WITH_APP_MT_BOOT 1
#define WITH_DEV_GIC 1
#define WITH_DEV_KEYS 1
#define WITH_DEV_LCM 1
#define WITH_DEV_MD_COM 1
#define WITH_DEV_VIDEO 1
#define WITH_LIB_DEBUG 1
#define WITH_LIB_HEAP 1
#define WITH_LIB_LIBC 1
#define WITH_LIB_LIBFDT 1
#define WITH_LIB_LIBSHOWLOGO 1
#define WITH_LIB_LIBUFDT 1
#define WITH_LIB_MBLOCK 1
#define WITH_LIB_PLAT_DBG_INFO 1
#define WITH_LIB_PTABLE 1
#define WITH_LIB_ZLIB 1
#define WITH_PLATFORM_COMMON_AEE_PLATFORM_DEBUG 1
#define WITH_PLATFORM_COMMON_ATF 1
#define WITH_PLATFORM_COMMON_BOOT 1
#define WITH_PLATFORM_COMMON_BOOT_LEGACY 1
#define WITH_PLATFORM_COMMON_LOADER 1
#define WITH_PLATFORM_COMMON_LOG_STORE 1
#define WITH_PLATFORM_COMMON_MD 1
#define WITH_PLATFORM_COMMON_PARTITION 1
#define WITH_PLATFORM_COMMON_PLINFO 1
#define WITH_PLATFORM_COMMON_SPM 1
#define WITH_PLATFORM_COMMON_STORAGE 1
#define WITH_PLATFORM_COMMON_STORAGE_BLKDEV 1
#define WITH_PLATFORM_COMMON_STORAGE_INTF 1
#define WITH_PLATFORM_COMMON_TIMER 1
#define USE_DTB_NO_DWS
#define MTK_EMMC_SUPPORT
#define MTK_SECURITY_SW_SUPPORT
#define MTK_VERIFIED_BOOT_SUPPORT
#define DEBUG 2
#endif
