#
# Makefile for misc devices that really don't fit anywhere else.
#


obj-y += st7701s_wvga_dsi_vdo_boe31.o
ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-$(CONFIG_PRIZE_LCD_BIAS_TPS65132) += -I$(srctree)/drivers/misc/mediatek/prize/lcdbias/tps65132



