name: Update module
on:
  workflow_dispatch:
  repository_dispatch:
    types: submodule-update
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update module
        run: |
          git submodule update --init --recursive --remote
          git config --global user.name "Android Boot Manager (GH Actions)"
          git config --global user.email "noreply@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "submodules_auto_update: Update submodule - ${{ github.event.client_payload.ref }}@${{ github.event.client_payload.module }}"
          git push
